### ISSUE TITLE
Add more advanced .csproj detection

### ISSUE THREAD

**Issue by hajekj** [Azure-App-Service/dotnetcore#16]
In the init_container.sh (https://github.com/Azure-App-Service/dotnetcore/blob/master/1.1.2/init_container.sh#L13) the detection is done by looking into the root directory for the .csproj file, however, if the project was created in Visual Studio, it will usually be nested in a folder, it would be great if lookup for such case was added by default. I am aware of the possibility to replace init_container.sh with your own, however it would make it easier for newly coming users.

**Comment by mohag** [comment]
Looking at the `web.config` if it is present might be useful. (Parsing it might not be easy though)

(It would be nice to load something from a `dotnet publish`)

**Comment by patricklee2** [comment]
we now use oryx to detection
