### ISSUE TITLE
Unable to use zip deploy with .NET core

### ISSUE THREAD

**Issue by fiveisprime** [Azure-App-Service/dotnetcore#21]
Looks like the image is only looking for source that was deployed via git: https://github.com/Azure-App-Service/dotnetcore/blob/master/2.0.5/init_container.sh#L25

This is sourced in the App Service extension: https://github.com/Microsoft/vscode-azureappservice/issues/338

**Comment by fiveisprime** [comment]
Ping on this. .NET core zipdeploy deployments are still broken from within the extension.

**Comment by joshgav** [comment]
I don't think this is related to git vs. zip deployments. A zip deployment with a `.csproj` file would work per the linked source. This is instead related to binary vs. source deployments; if the binary has already been compiled by the user and a `.csproj` file isn't also included the system doesn't know what to run. This would happen with git too, just typically people don't include binaries in git repos.

When doing a binary deployment you should specify an alternate start script with `az webapp ... --startup-script ...` and include in that script `dotnet exec your.dll`. When doing a source deployment you should be sure you haven't signaled to the platform to skip build, e.g. in an App Setting.

**Comment by fiveisprime** [comment]
The extension doesn't deploy the binary. It sets `SCM_DO_BUILD_DURING_DEPLOYMENT` then deploys the source expecting to be built, but the source is never copied to the correct directory and the build doesn't actually do anything.

The logs make you think it succeeded
![image](https://user-images.githubusercontent.com/1186948/51701350-1f434a00-1fc6-11e9-92bd-3a8468fd3f62.png)

But streaming the logs once the container comes up, shows that there's no app

![image](https://user-images.githubusercontent.com/1186948/51701398-3aae5500-1fc6-11e9-81c4-420bedcea773.png)

All requests result in a 404 because `hostingstart` was deleted as part of the deploy, but the app failed to copy/build/start.

**Comment by joshgav** [comment]
Thanks @fiveisprime. Can you point me to the repo you're using?

**Comment by fiveisprime** [comment]
I'm just using `$ dotnet new web`

**Comment by joshgav** [comment]
Looks like the bug may be in https://github.com/Azure-App-Service/dotnetcore/blob/master/2.0.5/init_container.sh#L29. The default output location for `dotnet build` is `./bin/Debug/netcoreapp2.2/dotnet.dll` but the script is looking in the repo root. If that's the problem it's fixed in Oryx.

Perhaps move the built DLL to the repo root after it's built and see if that helps?

**Comment by patricklee2** [comment]
i think this is fix with oryx
