### ISSUE TITLE
Container init should fail with an more explicit message if .csproj cannot be located

### ISSUE THREAD

**Issue by ArnaudBrousseau** [Azure-App-Service/dotnetcore#22]
The following message is really hard to spot unless you know where to look (in docker logs, which you have to explicitly enable) and what to look for:

https://github.com/Azure-App-Service/dotnetcore/blob/7bc7c1bcc0e0d67fb26c5bc9e0659332ec76c907/2.0.5/init_container.sh#L34

I spent a fair amount of time chasing down why my app wasn't starting properly on Linux despite "successful" deployment. It turned out to be because the `.csproj` wasn't at the root of my git directory.

Changes proposed:
* Make the message more explicit. Something like "Could not find your .csproj or .dll in /home/site/repository/"
* When a `.csproj` isn't found, abort/fail with the more explicit version of the message. I'm not sure that it's desirable to silently fallback to `/home/hostingstart/hostingstart.dll`. If it's a must-have to fall back to this default dll, then fine to let this item go: displaying a more explicit message is already a win
* Icing on the cake: display a warning if multiple `.csproj`/`.dll` are found in `/home/site/repository`. Something like "[WARNING] Found multiple .csproj or .dll files in /home/site/repository. Using the first one on the list (head -1)"

**Comment by patricklee2** [comment]
we now use oryx to detection
